### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by rfvgyhn** [jcoutch/Hangfire.RecurringDateRange#6]
Any chance of supporting .net core?

` Package Hangfire.RecurringDateRange 0.2.0.20 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Hangfire.RecurringDateRange 0.2.0.20 supports: net452 (.NETFramework,Version=v4.5.2)`

**Comment by jcoutch** [comment]
I just pushed a change to multi-target both .NET Standard 1.3 as well as .NET 4.5.2.  I need to make some modifications to the build, but hopefully I'll have that done today.  Sorry it's taken so long (life got in the way.)

**Comment by jcoutch** [comment]
I have a pre-release build available on Nuget.  All of the unit tests pass, but it has not been fully tested within a project.  I will be doing some testing in my own projects, but if you run across any issues, let me know.

https://www.nuget.org/packages/Hangfire.RecurringDateRange/0.2.1.45-ci
